version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: stepikpg
    environment:
      POSTGRES_DB: "stepik"
      POSTGRES_USER: "stepik"
      POSTGRES_PASSWORD: "stepik"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
