version: "3.9"
services:
  postgres:
    image: postgres:16.4-alpine
    container_name: testdb
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "stepik"
      POSTGRES_PASSWORD: "stepik"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    command: >
      postgres -c ssl=off
    networks:
      - stepik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stepik -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  stepik_network:
    driver: bridge
